name: 'release'

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Whether or not this is a pre-release'
        required: true
        default: false
        type: boolean

      title:
        description: 'The title of the release'
        required: false
        type: string

      release_name:
        description: 'The name of the release, uses the tag if not specified'
        required: false
        type: string

  workflow_call:
    inputs:
      prerelease:
        description: 'Whether or not this is a pre-release'
        required: true
        default: false
        type: boolean

      title:
        description: 'The title of the release'
        required: false
        type: string

      release_name:
        description: 'The name of the release, uses the tag if not specified'
        required: false
        type: string
jobs:
  package:
    name: 'Package'
    uses: ./.github/workflows/package.yml

  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    needs: 'package'
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Download vsix artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: vsix
      - name: 'Release'
        uses: 'marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ inputs.release_name }}
          prerelease: ${{ inputs.prerelease }}
          title: ${{ inputs.title }}
          files: |
            *.vsix
